#! /bin/bash
yum update -y
yum install httpd -y
yum install wget -y
service httpd start
chkconfig httpd on
cd /var/www/html
wget https://raw.githubusercontent.com/Andrews-repo/DEV/master/Basic%20Web%20Host/index.html
