AWSTemplateFormatVersion: 2010-09-09
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-062f7200baf2fa504"
      KeyName: "newkeypair"
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      InstanceType: 't2.micro'
      SecurityGroupIds:
        - sg-0da8c45dd859d8183
      UserData:
        Fn::Base64:
              !Sub
                #!/bin/bash
                sudo yum update -y
                sudo yum install httpd -y
                sudo yum install wget -y
                sudo yum install wget -y
                service httpd start
                chkconfig httpd on
                cd /var/www/html
                wget https://raw.githubusercontent.com/Andrews-repo/DEV/master/Basic%20Web%20Host/index.html
