AWSTemplateFormatVersion: 2010-09-09
Description: Creats and admin and an ec2 user and groups, as well as sets access keys.
Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: Admin
      LoginProfile:
        Password: Password1@
        PasswordResetRequired: yes
          

  MyUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: ec2User
      LoginProfile:
        Password: Password1@
        PasswordResetRequired: yes

  MyAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref "MyUser" 

  ec2AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref "MyUser2"    
 
  MyGroup:
    Type: AWS::IAM::Group  
    Properties:
        GroupName: Admin
        ManagedPolicyArns:
         - arn:aws:iam::aws:policy/AdministratorAccess
         - arn:aws:iam::aws:policy/job-function/Billing
  
  MyGroup2:
    Type: AWS::IAM::Group  
    Properties:
        GroupName: ec2fullaccess
        ManagedPolicyArns:
         - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  
  Admin:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'MyGroup'
      Users: [!Ref 'MyUser']
  
  EC2User:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'MyGroup2'
      Users: [!Ref 'MyUser2']

Outputs:
    AccessKey:
      Value: !Ref 'MyAccessKey'
      Description: AWS AccessKeyID of new user.
    
    SecretKey:
      Value: !GetAtt [MyAccessKey, SecretAccessKey]
      Description: AWSSecretAccessKey of new user. 
    
    AccessKey:
      Value: !Ref 'ec2AccessKey'
      Description: AWS AccessKeyID of new ec2 user.
    
    SecretKey:
      Value: !GetAtt [ec2AccessKey, SecretAccessKey]
      Description: AWSSecretAccessKey of new ec2 user.
