AWSTemplateFormatVersion: 2010-09-09

Description: This script will create an ec2 install, and install the software to run the fortune node app.

Resources:
  myENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: A nice description.
      SourceDestCheck: 'false'
      GroupSet:
        - sg-055c055ea1f7b8c99
      SubnetId: subnet-b60753fa   
  
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2c
      ImageId: "ami-077e31c4939f6a2f3"
      KeyName: "keypairMAY"
      IamInstanceProfile: "DynamoDBfullaccessEC2"
      Monitoring: Yes
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo touch .bash_profile
          sudo yum update -y
          sudo yum install -y git
          cd /home/ec2-user
          sudo mkdir FortuneApp
          cd FortuneApp
          git init
          git pull https://github.com/Andrews-repo/FortuneSite          
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install node
          npm install aws-sdk
          npm install express --save
          npm install async --save
          npm install body-parser --save
          npm install ejs --save
          npm install random-number-between --save
          npm install request --save
          npm install pm2 -g --save
          node FortunesCreateTable.js
          node LoadFortunes2.js
          node FortunesItemOps2.js
          pm2 start server.js
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      InstanceType: 't2.micro'
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref myENI
          DeviceIndex: 0 
